### ISSUE TITLE
/nix/store/.../.ruby-version': No such file or directory

### ISSUE THREAD

**Issue by leoc** [bobvanderlinden/nixpkgs-ruby#148]
I just tried to reconfigure my current project settings by deleting `flake.[nix,lock]` and `.envrc` and then running:

`nix flake init --template github:bobvanderlinden/nixpkgs-ruby#`

Unfortunately I get this error:

```
cd .
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/a2gnsay8asfn2kqghz12nhw196cnmf8h-source/pkgs/stdenv/generic/make-derivation.nix:333:7

       … while evaluating attribute 'buildInputs' of derivation 'nix-shell'

         at /nix/store/a2gnsay8asfn2kqghz12nhw196cnmf8h-source/pkgs/stdenv/generic/make-derivation.nix:380:7:

          379|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          380|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          381|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       error: getting status of '/nix/store/8zs2spnfbkayjydmdyspln4gscbc035q-source/.ruby-version': No such file or directory
```

Is there anything I missed?

EDIT:

I am using this `flake.nix`. Basically the template with `gems` commented out.

<details><summary>Details</summary>
<p>

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    nixpkgs-ruby.url = "github:bobvanderlinden/nixpkgs-ruby";
    nixpkgs-ruby.inputs.nixpkgs.follows = "nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      self,
      nixpkgs,
      nixpkgs-ruby,
      flake-utils,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        ruby = nixpkgs-ruby.lib.packageFromRubyVersionFile {
          file = ./.ruby-version;
          inherit system;
        };
        # gems = pkgs.bundlerEnv {
        #   name = "gemset";
        #   inherit ruby;
        #   gemfile = ./Gemfile;
        #   lockfile = ./Gemfile.lock;
        #   gemset = ./gemset.nix;
        #   groups = [
        #     "default"
        #     "production"
        #     "development"
        #     "test"
        #   ];
        #   extraConfigPaths = [ "${./.}/.ruby-version" ];
        # };

      in
      {
        devShell =
          with pkgs;
          mkShell {
            buildInputs = [
              # gems
              ruby
              bundix
            ];
          };
      }
    );
}

```

</p>
</details> 

EDIT2: I now found #60, but the proposed fix is already present in the `flake.nix`?

**Comment by bobvanderlinden** [comment]
Most ruby projects have a `.ruby-version` file to indicate which version of ruby to use. The default template also looks for this file.

So if it is not there yet, create it and also make sure to stage, add or commit it in git(!). Nix flakes are not able to find files in a git repository of it is not part of git.

Alternatively, if you don't want a `.ruby-version`, you can replace the `ruby = ...` option with `ruby = nixpkgs-ruby.packages.${system}."ruby-3";`

**Comment by leoc** [comment]
Ah i forgot to mention. We have been using rvm, rbenv and co so this file already exists in our project. Still I get the error above. 🥲

**Comment by bobvanderlinden** [comment]
Ah ok. Usually with such errors it's because I haven't added the file to git yet. If that's not the problem, then it might help to check what's in /nix/store/8zs2spnfbkayjydmdyspln4gscbc035q-source/.

**Comment by dwradcliffe** [comment]
I ran into this as well, and it was indeed because `.ruby-version` wasn't tracked by git yet.
Maybe it would be good to mention this in the readme.
But also, is there a reason that this relies on git tracking?

**Comment by bobvanderlinden** [comment]
I've added the suggestion to the readme 👍
