### ISSUE TITLE
Broken for usage via import, README code fails

### ISSUE THREAD

**Issue by purcell** [bobvanderlinden/nixpkgs-ruby#5]
I see there's a recent commit along the lines of "dropped default.nix" support, which probably explains the breakage I am seeing locally after updating `nixpkgs-ruby`. How is one to use this now? The README seems outdated.

**Comment by bobvanderlinden** [comment]
The repository is now based on Nix flakes. You can still use the older versions using a specific commit. I've updated the readme the workflow surrounding flakes.

**Comment by purcell** [comment]
Understood — I think it was a bolder choice when I first opened this issue. 😄
